export const APP_CONSTANTS = {

  DEFAULT_CODE: "GP01",

  API_ENDPOINTS: {
  }
};


export const DEFAULT_GROUP_CODE = APP_CONSTANTS.DEFAULT_CODE;
export const API_ENDPOINTS = APP_CONSTANTS.API_ENDPOINTS;
